aspect-build/rules_swc

swc/private/swc.bzl
https://swc.rs/docs/usage/cli#--config-file
=> fix: flag to pass swcrc is --config-file

examples/rc/.swcrc, examples/rc/BUILD.bazel, examples/rc/src/BUILD.bazel, examples/rc/src/expected.js, examples/rc/src/expected.js.map, examples/rc/src/in.ts, swc/private/swc.bzl
maybe something changed upstream since that code was written?
The newly added example shows it working without that.
Fixes #11
=> fix: don't relativize paths to the swcrc location

swc/private/swc.bzl
This PR cleans up a few things:
1) Removes some duplication between the outdir vs out-files branches
2) Removes some unused output lists
3) Changes how we emit progress_message to avoid constructing strings at analysis time. The message will change slightly for the per-file action (it will have the full src path instead of the short path) but these actions are so quick that I doubt anyone will notice.
=> Clean up rule implementation

examples/directory/BUILD.bazel, examples/directory/test.sh, examples/filegroup/check_outputs.sh, swc/private/swc.bzl
While looking into the `ts_project` transpiler ...
=> add tests, support out_dir+output_dir

scripts/filter.jq, swc/private/versions.bzl, swc/tests/versions_test.bzl
Thanks @Aghassi for the mirror script filter.jq fix
=> chore: add v1.3.22 and v1.3.23

examples/custom_outs/BUILD.bazel, examples/custom_outs/b.mts, swc/private/swc.bzl
=> fix: map alternative ts file extensions

.bcr/config.yml, .bcr/metadata.template.json, .bcr/presubmit.yml, .bcr/source.template.json, .github/workflows/workspace_snippet.sh, WORKSPACE, docs/BUILD.bazel, docs/repositories.md, docs/swc.md, examples/macro/ts_project.bzl, swc/BUILD.bazel, swc/defs.bzl, swc/dependencies.bzl, swc/extensions.bzl, swc/private/swc.bzl, swc/repositories.bzl
=> chore: add .bcr for auto-publishing to the registry

scripts/mirror_releases.sh, swc/private/versions.bzl
Failure was detected by bcr presubmit in https://buildkite.com/bazel/bcr-presubmit/builds/835#01858d36-bb45-4846-9122-b934f1b83b8f
=> fix(windows): remove exe extension in platforms lookup

.bcr/metadata.template.json
Note, the homepage link will work as soon as https://github.com/aspect-build/silo/pull/1127 lands
=> chore: update bcr homepage

README.md
=> docs: fix reference to non-existent target

examples/custom_outs/BUILD.bazel
We can cleanup a workaround where we generated a swcrc file
=> chore: --config is working now

examples/filegroup/check_outputs.sh, examples/rc/src/expected.js.map, swc/private/swc.bzl
fixes #166 
That's the last 1.0 blocker :)
Thanks @realtimetodie
=> Fix sourcemaps

examples/out_dir/BUILD.bazel, examples/out_dir/expected/a.js, examples/out_dir/expected/a.js.map, examples/out_dir/expected/b.js, examples/out_dir/expected/b.js.map, examples/root_dir/BUILD.bazel, examples/root_dir/expected/a.js, examples/root_dir/expected/a.js.map, examples/root_dir/expected/b.js, examples/root_dir/expected/b.js.map
These are bugging me now, and I think show more issues that #176 should fix.
=> test: use write_source_files where possible

docs/swc.md, swc/private/swc.bzl
=> refactor: no default value for source_root

swc/private/toolchains_repo.bzl, swc/private/versions.bzl
Also remove two platforms they've stopped publishing binaries for.
---
=> chore: update swc version mirror

WORKSPACE, e2e/smoke/WORKSPACE.bazel, swc/repositories.bzl
See https://github.com/aspect-build/rules_js/issues/817
=> fix: rename LATEST_VERSION to LATEST_SWC_VERSION

MODULE.bazel, examples/rc/src/expected.js, examples/rc/src/expected.js.map, swc/private/versions.bzl, swc/tests/versions_test.bzl
See https://github.com/swc-project/swc/issues/7304
=> fix: remove swc v1.3.56

swc/private/swc.bzl
I think this is even in 5.1: https://github.com/bazelbuild/bazel/commit/50bb742fc35c04ab422a7ce723160b27d6900e6c
---
=> perf: use starlark string.removeprefix

swc/private/swc.bzl
This makes my test case go from about 15-20 to 8s.
---
=> perf: reduce extension swap when finding alternate extension output

swc/private/swc.bzl
Just trying to cleanup to simplify the analysis phase.
=> refactor: remove unnecessary default param values

e2e/smoke/MODULE.bazel, swc/extensions.bzl
- Bug fix (change which fixes an issue)
- New feature or functionality (change which adds functionality)
=> feat: add custom swc toolchain support for bzlmod

.github/workflows/release.yml
=> build: upgrade release workflow

swc/private/swc.bzl
Aligning with rules_ts for now, can maybe move these into a common location later.
---
=> refactor: align path utils with rules_ts

.pre-commit-config.yaml, BUILD.bazel, e2e/smoke/BUILD.bazel, examples/opaque_src/BUILD.bazel, examples/out_dir/BUILD.bazel, examples/plugins/BUILD.bazel, examples/root_dir/BUILD.bazel, examples/source_map_support/BUILD.bazel, examples/source_root/BUILD.bazel, examples/transitive/app/BUILD.bazel, internal_deps.bzl, swc/defs.bzl
Pre-factor from https://github.com/aspect-build/rules_swc/pull/253.
Stacked on top of https://github.com/aspect-build/rules_swc/pull/254.
=> chore: bump to buildifier 6.4.0

.bazelversion, .gitignore, MODULE.bazel, swc/dependencies.bzl
Pre-factor from https://github.com/aspect-build/rules_swc/pull/253.
Strange plugin test failure in #253 so I'm reducing the change set to narrow down what is causing it.
=> chore: bump to Bazel 7

.github/workflows/ci.bazelrc, .github/workflows/ci.yaml, BUILD.bazel, docs/BUILD.bazel, swc/BUILD.bazel, swc/private/is_bazel_7_or_greater.bzl
Pre-factor from https://github.com/aspect-build/rules_swc/pull/253.
=> chore: update GHA CI to latest pattern for testing Bazel 6/7, bzlmod on/off, linux/darwin/windows

MODULE.bazel, e2e/smoke/MODULE.bazel
Pre-factored from https://github.com/aspect-build/rules_swc/pull/253
=> chore: misc cleanup

.aspect/bazelrc/ci.bazelrc, .aspect/bazelrc/correctness.bazelrc, .aspect/bazelrc/javascript.bazelrc, .aspect/bazelrc/performance.bazelrc, .github/workflows/bazel6.bazelrc, .github/workflows/bazel7.bazelrc, BUILD.bazel, MODULE.bazel, WORKSPACE, docs/swc.md, e2e/smoke/MODULE.bazel, examples/plugins/BUILD.bazel, swc/BUILD.bazel, swc/defs.bzl, swc/dependencies.bzl, swc/private/is_bazel_7_or_greater.bzl, swc/private/swc.bzl, swc/private/swc_plugin.bzl
---
- New feature or functionality (change which adds functionality)
**For changes visible to end-users**
- Breaking change (this change will force users to change their own code or config)
- Suggested release notes are provided below:
=> feat: upgrade to rules_js 2.0

swc/private/swc.bzl
=> perf: use shared args for swcrc, source_root params

.bazelignore, .bazelrc, .github/workflows/ci.yaml, MODULE.bazel, WORKSPACE, docs/.bazelversion, docs/BUILD.bazel, docs/MODULE.bazel, docs/repositories.md, docs/swc.md
It has a hard-coded dependency on compiling protoc from source and makes me mad
---
=> refactor: remove stardoc from root repository

.aspect/cli/config.yaml, .aspect/workflows/config.yaml, .bazeliskrc, .github/workflows/ci.yaml
=> ci: add workflows

swc/private/BUILD.bazel
Found when using a raw starlark_doc_extract rule
=> fix(docgen): add missing deps

MODULE.bazel, README.md, swc/extensions.bzl
=> chore: turn on tools_telemetry

MODULE.bazel
=> chore: upgrade tools_telemetry to 0.2.6
