aspect-build/rules_swc

swc/private/swc.bzl
By default, swc outputs `Successfully compiled 1 file with swc.` when compilation is successful, this extra logging isn't really needed under bazel, and leads to polluted logs when many `swc` rules are used.
Add the `-q` flag by default to quieten down the output, errors will still be printed:
```
$ bazel build //examples/simple:transpile
INFO: Analyzed target //examples/simple:transpile (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
ERROR: /Users/matthew.mackay/robinhood/rules_swc/examples/simple/BUILD.bazel:13:4: Transpiling with swc //examples/simple:transpile [swc examples/simple/in.ts] failed: (Exit 1): _cli_launcher.sh failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6/bin/swc/_cli_launcher.sh -q examples/simple/in.ts --out-file …
```
=> fix(swc): suppress swc output by default

swc/private/toolchains_repo.bzl
The tool is only used in execution context. When this line is included, the build will fail when targetting QNX for example
=> fix: don't try to declare swc toolchain for target platform

docs/swc.md, examples/custom_outs/BUILD.bazel, swc/swc.bzl
This is more obvious as an argument to ts_project#transpiler
=> rename swc_rule to swc_transpiler

.github/workflows/workspace_snippet.sh, internal_deps.bzl, swc/dependencies.bzl
Required per https://github.com/bazel-contrib/SIG-rules-authors/issues/11
=> Update github archive URLs to have stable SHAs

swc/private/swc.bzl
As the `args` action is reused, each file (and therefore iteration) contains the existing args of the previous run. On larger projects (or OS where the command line length limit is short), this causes an overflow.
Use a new `args` action for each iteration.
Closes #21 
See https://github.com/bazelbuild/rules_nodejs/issues/3311 for further info
=> fix(core): use new args action for each iteration

swc/BUILD.bazel
When a user's root-level `package.json` includes `"type": "module"`, building with `rules_swc` produces the following error:
```
require('@swc/cli')
^
ReferenceError: require is not defined in ES module scope, you can use import instead
```
Renaming the `main.js` file to `main.cjs` resolves this issue.
_See minimal reproduction of the issue: https://github.com/Nick-Mazuk/bazel-swc-es6_
=> Rename main.js to main.cjs

.github/workflows/workspace_snippet.sh, WORKSPACE, examples/transitive/BUILD.bazel, examples/transitive/app/BUILD.bazel, examples/transitive/app/a.ts, examples/transitive/expected, examples/transitive/lib_b/BUILD.bazel, examples/transitive/lib_b/b.ts, examples/transitive/lib_c/BUILD.bazel, examples/transitive/lib_c/c.ts, swc/private/swc.bzl, swc/private/versions.bzl
=> Propagate runfiles

internal_deps.bzl, swc/dependencies.bzl
This lets renovate understand our Bazel dependencies.
Note, this will soon be unneeded when https://github.com/renovatebot/renovate/pull/16003 lands and is released.
In the meantime we are near launch and want to keep our stuff updated.
=> chore: remove maybe()

swc/dependencies.bzl
1.0.0-rc.2 breaks since we need the fix in https://github.com/aspect-build/rules_js/pull/323
=> chore: update to aspect_rules_js to latest commit hash

swc/cli_repositories.bzl, swc/pnpm-lock.yaml
I was running into an issue with source maps and found it was identical to https://github.com/sveltejs/svelte/issues/7728.  The fix over there was updating `source-map` (since `source-map@0.7.3` checks for the environment by the existence of `fetch`, which is now included in Node, and `source-map@0.7.4` replaces this with a `window` check).  Since `source-map` is a transitive dependency of `@swc/cli`, it's part of the `pnpm-lock.yaml` included, but it's currently locked to `source-map@0.7.3`.  So, this PR was just the result of updating that, which fixes the source map issue.
=> fix: update transitive `@swc/cli` dependencies

docs/swc.md, swc/defs.bzl, swc/private/swc.bzl
This lets the caller do something else with them, without having to hard-code which paths swc knows how to handle.
=> feat: transpiler function returns unused srcs

docs/swc.md, swc/defs.bzl, swc/private/swc.bzl
Reverts aspect-build/rules_swc#116
Design wasn't thorough and there's a critical flaw with filegroups in srcs, we can't really predict this way.
=> Revert "feat: transpiler function returns unused srcs"

WORKSPACE, examples/custom_outs/BUILD.bazel, examples/paths/.swcrc, examples/paths/BUILD.bazel, examples/paths/expected.js, examples/paths/src/index.ts, examples/paths/src/modules/moduleA/index.ts, examples/paths/tsconfig.json, swc/private/testing.bzl
We shouldn't have an example that's red in the editor, that's just confusing users with a bad pattern
=> chore: cleanup paths example

swc/private/BUILD.bazel, swc/private/swc.bzl
Prevents the stdin handle from waiting in an infinite loop for the read stream to finish
Fixes #141
=> fix(windows): mimic an empty stdin input

swc/private/swc.bzl
Context: this unblocks migration of BuildBuddy to `rules_js`. We build our app externally like `bazel build @com_github_buildbuddy_io_buildbuddy//enterprise/app:app_bundle` when deploying via our internal repo, and this is broken because the current logic in rules_swc results in files being written to the wrong path.
Before, we'd get an error from esbuild like `app.tsx: ERROR: Could not resolve "./root/root"`, and inspecting the sandbox dir after building with `--sandbox_debug`, the tree would look like this (filtering just to `app.tsx` and `root.js` here which are the main relevant files):
```
$(bazel-sandbox)/buildbuddy_internal/
- bazel-out/k8-opt/bin/
- external/com_github_buildbuddy_io_buildbuddy/
- enterprise/app/
- app.tsx  # esbuild entrypoint
- …
```
=> Fix package-relative paths for external sources

README.md
Renames the Bazel target to @aspect_rules_swc//swc:swc_compile
https://github.com/aspect-build/rules_swc/issues/88#issuecomment-1410957914
=> docs: Rename Bazel target swc_compile

MODULE.bazel, WORKSPACE, examples/filegroup/BUILD.bazel, examples/filegroup/a.ts, examples/filegroup/b.ts, examples/paths/.swcrc, examples/paths/BUILD.bazel, examples/paths/expected.js, examples/paths/src/index.ts, examples/rc/src/expected.js, examples/rc/src/expected.js.map, package.json, swc/defs.bzl, swc/private/swc.bzl, swc/private/versions.bzl, swc/repositories.bzl, swc/tests/versions_test.bzl
Fixes an issue where the sourceMappingURL comment was not added to the output.
Fixes https://github.com/aspect-build/rules_swc/issues/146
=> fix: Sourcemap links are not generated

WORKSPACE, docs/swc.md, examples/plugins/BUILD.bazel, examples/plugins/expected_rc.js_, examples/plugins/expected_rcdict.js_, examples/plugins/expected_simple.js_, examples/plugins/in.ts, examples/plugins/minify.swcrc, examples/plugins/package.json, examples/pnpm-lock.yaml, examples/pnpm-workspace.yaml, package.json, swc/BUILD.bazel, swc/defs.bzl, swc/private/BUILD.bazel, swc/private/swc.bzl, swc/private/swc_plugin.bzl, swc/providers.bzl
This PR implements all of the wiring necessary to use SWC plugins.
- Add a `swc_plugin` macro/rule pair that creates a target with the necessary providers:
- a `DefaultInfo` pointing at a wasm file or an npm package containing a wasm file as the `main` entrypoint in the `package.json`
- a new `SwcPluginConfigInfo` holding the plugin configuration
- Add a `plugins` attr to `swc_compile` and `swc`, taking a list of plugin targets, along with helpers to inject the plugin config.
=> Add support for plugins

docs/swc.md, e2e/smoke/BUILD.bazel, examples/generate_swcrc/BUILD.bazel, examples/paths/BUILD.bazel, examples/plugins/BUILD.bazel, examples/rc/src/BUILD.bazel, examples/rcdict/BUILD.bazel, examples/simple/BUILD.bazel, swc/defs.bzl
BREAKING CHANGE
It's too magical for us to discover them with a glob, making it harder to read the BUILD file and know what's going on
=> refactor: force users to explicitly provide srcs

examples/custom_outs/BUILD.bazel, examples/filegroup/BUILD.bazel, examples/out_dir/BUILD.bazel, examples/root_dir/BUILD.bazel
Also use boolean rather than string where possible.
=> refactor: only use underlying rule where required

WORKSPACE, examples/custom_outs/BUILD.bazel, examples/paths/.swcrc, examples/paths/BUILD.bazel, examples/paths/expected.js, examples/paths/tsconfig.json, package.json, swc/private/swc.bzl, swc/private/versions.bzl, swc/tests/versions_test.bzl
The `--config` flag was renamed to `--config-json`, so plugin support will only work with versions >= 1.3.36 going forward.
@realtimetodie It looks like module path handling may have been broken by swc-project/swc#6930, do you understand what is going on here?
```
Executing tests from //examples/paths:test_test
-----------------------------------------------------------------------------
5c5
< const _moduleA = require("../../../../../home/codespace/.cache/bazel/_bazel_codespace/8740319a112a77c7681d8f1244e5cd69/sandbox/linux-sandbox/11/execroot/aspect_rules_swc/examples/paths/src/modules/moduleA");
---
> const _moduleA = require("./modules/moduleA");
FAIL: files "examples/paths/src/index.js" and "examples/paths/expected.js" differ. 
@//examples/paths:expected.js is out of date. To update …
```
=> chore: update to swc v1.3.36

WORKSPACE, docs/repositories.md, package.json, swc/repositories.bzl
This means we don't have to mirror hashes an extra time when we add a new swc version. Move this to the documentation instead.
Note, this means we don't have test coverage for these two attributes anymore. If we really want that we could add another e2e for it.
=> chore: simplify WORKSPACE

docs/swc.md, examples/source_root/BUILD.bazel, examples/source_root/expected.js, examples/source_root/expected.js.map, examples/source_root/expected_subdir.js, examples/source_root/expected_subdir.js.map, examples/source_root/in.ts, examples/source_root/src/subdir.ts, swc/private/swc.bzl
Allows the user to specify a custom location where a debugger should locate source files.
This imitates the TSConfig `sourceRoot` configuration option
https://www.typescriptlang.org/tsconfig#sourceRoot
Example
```starlark
swc(
name = "compile",
source_maps = True,
source_root = "https://my-website.com/debug/source/",
)
```
The `source_root` attribute is optional.
Related
- #176
=> feat: add a new source_root attribute

examples/filegroup/BUILD.bazel, examples/filegroup/check_outputs.sh, examples/filegroup/sub/c.ts, examples/out_dir/BUILD.bazel, examples/out_dir/expected/a.js.map, examples/out_dir/expected/b.js.map, examples/out_dir/expected/sub/c.js, examples/out_dir/expected/sub/c.js.map, examples/out_dir/sub/c.ts, examples/package.json, examples/pnpm-lock.yaml, examples/rc/src/expected.js.map, examples/root_dir/BUILD.bazel, examples/root_dir/expected/a.js.map, examples/root_dir/expected/b.js.map, examples/root_dir/expected/sub/c.js, examples/root_dir/expected/sub/c.js.map, examples/root_dir/src/sub/c.ts, examples/source_map_support/BUILD.bazel, examples/source_map_support/defs.bzl, examples/source_map_support/stack-trace-support.js, examples/source_map_support/test/BUILD.bazel, examples/source_map_support/test/a.ts, examples/source_map_support/test/b.ts, examples/source_root/expected_subdir.js.map, swc/private/swc.bzl
This makes the sourcemap `sources` and `sourceRoot` align with tsc (when invoked from `ts_project` EDIT: and not in a worker, and properly sandboxed, and probably other conditions for it to be the "normal" case). This is comparing a `ts_project` in silo, tsc vs swc
~~The `sourcesContent` is relative to the `swc(root_dir)`, the `sourceRoot` is relative to the workspace root and includes the `root_dir`.~~
The map file `sources` is relative to the map, so when there is 1 .map per .js it is just the filename.
The `sourceRoot` is basically just a prefix and we just set it to what the user specifies (https://github.com/aspect-build/rules_swc/pull/177)
=> fix: set sourcemap root to the workspace relative root_dir

examples/filegroup/check_outputs.sh, examples/out_dir/expected/a.js.map, examples/out_dir/expected/b.js.map, examples/out_dir/expected/sub/c.js.map, examples/rc/src/expected.js.map, examples/root_dir/expected/a.js.map, examples/root_dir/expected/b.js.map, swc/private/swc.bzl
The spec says the "sourceRoot" is optional, so empty should be the same as not specified.
See https://sourcemaps.info/spec.html#h.qz3o9nc69um5
=> fix: do not specify empty --source-root arg

swc/private/swc.bzl
Prevents adding the --source-file-name option and --source-root option when source maps generation is disabled.
=> refactor: prevent adding unused source maps options

.github/workflows/ci.yaml
Adds the windows runner to the matrix strategy of the test workflow job.
Matrix implementation inspired by https://github.com/aspect-build/bazel-lib (kudos to @gregmagolan)
Fixes https://github.com/aspect-build/rules_swc/issues/185
=> ci: add the windows runner to the matrix strategy

MODULE.bazel, swc/private/versions.bzl, swc/tests/versions_test.bzl
The next release (v1.3.44) starts to fail tests on ci macos.
=> chore: mirror swc version 1.3.42

MODULE.bazel, swc/dependencies.bzl
Windows fix. BCR should be green now for Windows with this change.
---
=> chore: bump rules_js dep to 1.29.2 to pickup Windows fix

docs/tsconfig.md, examples/generate_swcrc/BUILD.bazel, examples/generate_swcrc/package.json, examples/generate_swcrc/write_swcrc.js, examples/pnpm-lock.yaml
It was added in version 2.4.0, see
https://github.com/Songkeys/tsconfig-to-swcconfig#cli
This will make it more palatable for ts_project users.
---
=> refactor: adopt tsconfig-to-swcconfig CLI

docs/repositories.md, scripts/mirror_releases.sh, swc/repositories.bzl
additionally, updates `mirror_releases.sh` so it can be run to retrieve a single specific version and its hashes.
---
- Documentation (updates to documentation or READMEs)
**For changes visible to end-users**
- Relevant documentation has been updated
- Manual testing; please provide instructions so we can reproduce:
- Executed `mirror_releases.sh` both with a version to search for and without, to ensure it still worked in both cases.
=> doc: Add documentation for using your own swc version

examples/source_map_support/BUILD.bazel, internal_deps.bzl, swc/BUILD.bazel, swc/dependencies.bzl, swc/private/BUILD.bazel, swc/private/maybe.bzl
Was likely just forgotten in 4e44b7368ccda4422c8d00597fda59edb203be35.
- Bug fix
- Untested (review only).
=> Fix bzl_library dependencies of dependencies.bzl

.github/workflows/mirror.yml, docs/repositories.md, scripts/filter.jq, scripts/mirror_releases.sh, swc/repositories.bzl
We fall behind SWC releases quite quickly
---
Manually run the workflow after merge
=> feat: automate release mirroring

swc/private/swc.bzl, swc/private/swc_plugin.bzl
When looking at traces or profiles a unique name really helps.
---
=> refactor: rename _impl methods with unique name

swc/private/swc.bzl
=> perf: calculate js_outs once outside srcs loop

swc/private/swc.bzl
https://github.com/aspect-build/rules_swc/commit/6bf6610494cbb7589b5e34f3d834abd8c19e55d0 made a noticeable difference so I think we should do similar elsewhere, especially when iterating over potentially large arrays.
---
=> perf: avoid creating unnecessary large or temp arrays

swc/private/swc.bzl
This made a significant difference when used on a large array of sources.
See https://github.com/bazelbuild/bazel-skylib/issues/487
---
=> perf: remove use of paths.replace_extension

swc/private/swc.bzl
=> refactor: simplify swc_action(inputs) creation

.bazeliskrc
It doesn't have a windows release and we don't use it here.
=> ci(presubmit): do not use aspect-cli

.prettierignore, examples/package.json, examples/paths/BUILD.bazel, examples/paths/expected_tsc/index.js, examples/paths/expected_tsc/modules/moduleA/index.js, examples/paths/expected_tsc/modules/moduleB/index.js, examples/paths/tsconfig.json, examples/pnpm-lock.yaml
The SWC project claims that their emit should match, so this helps us reason about what is "correct" behavior. We can just point them at the golden files to show what `tsc` does.
=> chore: add test producing the typescript source-of-truth

examples/allow_js/BUILD.bazel, examples/allow_js/expected.js, examples/allow_js/in.js, swc/private/swc.bzl
- Bug fix (change which fixes an issue)
=> fix: support .js inputs without out_dir

.github/workflows/ci.bazelrc, MODULE.bazel, WORKSPACE, docs/repositories.md, docs/swc.md, internal_deps.bzl
Pre-factor from https://github.com/aspect-build/rules_swc/pull/253.
=> chore: bump to latest stardoc

MODULE.bazel, swc/dependencies.bzl
bazel-lib 2.7.3 has a bad URL in coreutils for darwin x86
=> chore: bump miminum dep to aspect_bazel_lib 2.7.6

MODULE.bazel, swc/dependencies.bzl
aspect_bazel_lib min bump goes along with rules_js bump in https://github.com/aspect-build/rules_js/pull/1763 to pick up fix for copy_to_directory that affects npm_package: https://github.com/aspect-build/bazel-lib/pull/857.
=> chore: bump to rules_js 2.0.0-rc1 and minimum aspect_bazel_lib 2.7.7

swc/dependencies.bzl
Ensures users pick up https://github.com/bazelbuild/rules_nodejs/pull/3760 fix which is a footgun that should be avoided.
=> chore: bump minimum rules_nodejs to 6.2.0

swc/private/swc.bzl
For compatibility with the latest rules_js v2
=> fix: use latest rules_js gather_transitive_sources signature

e2e/smoke/MODULE.bazel
Tripped over this in rules_ts where I copied the snippet, and the registration leaked into userland.
It's enough to add the tag_class, then rules_swc reads it when it registers.
---
=> chore: remove unneeded registration

MODULE.bazel, swc/dependencies.bzl
allows rules_swc to go out of RC
=> chore: bump rules_js dependency to 2.0 final

examples/genrule/.swcrc, examples/genrule/BUILD.bazel, examples/genrule/check_outputs.sh, swc/private/swc.bzl
Minor fix aligning with rules_ts while trying to reproduce #274
---
=> fix: align pre-calculated outputs with rules_ts

examples/root_dir/expected/a.js.map.golden, examples/root_dir/expected/b.js.map.golden, examples/root_dir/expected/sub/c.js.map.golden, examples/source_root/expected_subdir.js.map.golden, swc/private/swc.bzl
Fixes an issue where the `root_dir` was not considered when computing the paths in source maps. The issue is visible in the examples by checking the computed paths against the actual paths of the source files in the Bazel output directory.
---
=> fix: consider root dir for source maps paths

swc/private/swc.bzl
=> perf: align utils funcs with latest from rules_ts

.prettierignore, MODULE.bazel, examples/plugins/BUILD.bazel, examples/plugins/package.json, examples/pnpm-lock.yaml, swc/repositories.bzl
Passes all tests with only minor modifications. Still using a manually specified+tested version instead of `LATEST[0]` for now.
---
- Suggested release notes appear below: yes
The `LATEST_SWC_VERSION` has now been set to `v1.7.40`.
=> feat: upgrade default swc version to v1.7.40

examples/allow_js/BUILD.bazel, examples/allow_js/expected.cjs, examples/allow_js/expected.jsx, examples/allow_js/expected.mjs, examples/allow_js/in.cjs, examples/allow_js/in.d.ts, examples/allow_js/in.jsx, examples/allow_js/in.mjs, swc/private/swc.bzl
Partially in preparation for https://github.com/aspect-build/rules_swc/pull/270 where I hope to also fix the issue demonstrated in https://github.com/jfirebaugh/rules_ts/commit/42bb97dad0abc4d3c0c8f701ee0e88a885a346a6.
This does fix one minor/uncommon issue when you have multiple input+output files only differing in extension (`in.{jsx,mjs,cjs}`), see the `alt_js_out` change.
---
=> refactor: align js file extension logic with rules_ts

docs/swc.md, swc/defs.bzl, swc/private/swc.bzl
=> feat: add default_ext

docs/swc.md, examples/allow_js/BUILD.bazel, examples/allow_js/expected.ts, examples/allow_js/in_ts.ts, swc/defs.bzl, swc/private/swc.bzl
This allows `swc` to more faithfully mimic the behavior of tsc when used as a transpiler with `ts_project`. A `ts_project` wrapper macro can do:
```
transpiler = partial.make(
swc,
out_dir = out_dir,
root_dir = root_dir,
allow_js = allow_js,
source_maps = source_map,
...,
)
```
=> feat: Add `allow_js` attribute

.aspect/bazelrc/convenience.bazelrc, .aspect/bazelrc/correctness.bazelrc, .aspect/bazelrc/performance.bazelrc, .github/workflows/bazel6.bazelrc, .github/workflows/bazel7.bazelrc, MODULE.bazel, examples/filegroup/BUILD.bazel, examples/genrule/BUILD.bazel, swc/dependencies.bzl
Fix windows before tagging a release, see [failures at HEAD](https://github.com/aspect-build/rules_swc/actions/runs/14205075208/job/39800834303) 
---
- Suggested release notes appear below: yes
Upgrade bazel-lib to include https://github.com/bazel-contrib/bazel-lib/pull/969
- Manual testing; include `windows` in the branch name to trigger windows CI
=> chore: upgrade bazel-lib to include windows tar fix

docs/repositories.md, e2e/smoke/.bazelignore, e2e/smoke/.npmrc, e2e/smoke/MODULE.bazel, e2e/smoke/package.json, e2e/smoke/pnpm-lock.yaml, swc/extensions.bzl, swc/repositories.bzl
Add support for `swc_version_from` to bzlmod extension.
---
- Suggested release notes appear below: yes
Add support for `swc_version_from` to bzlmod extension.
=> fix: add support for `swc_version_from` to bzlmod extension

swc/private/versions.bzl
Add integrity hashes for `v1.11.18`. 
This was motivated by [swc-project/swc#10313](https://github.com/swc-project/swc/issues/10313) which caused plugins to not be loaded on Linux in `v1.11.16`.
---
- Suggested release notes appear below: yes
Add integrity hashes for `v1.11.18`. 
=> Add integrity hashes for `v1.11.18`

swc/private/resolved_toolchain.bzl
Bazel doesn't recognize this as of https://github.com/bazelbuild/bazel/commit/f53608ac3dbfd02cecb4bb78a138badb0d84e311.
This causes @bazelbuild/examples CI failure: https://github.com/bazelbuild/examples/issues/610.
- Suggested release notes appear below: no
- Manual testing; please provide instructions so we can reproduce: see https://github.com/bazelbuild/examples/issues/610.
=> Remove bad incompatible_use_toolchain_transition reference.
